version: "3"

dotenv:
  - "web/.env.local"
  - "desktop/services/.env.local"

tasks:
  hostd:
    dir: "desktop/services"
    cmds:
      - cargo run --bin hostd
  hostd:remote:
    dir: "desktop/services"
    cmds:
      - cargo run --bin hostd -- --cloudflare-url "wss://remoterg.the7uya.workers.dev/api/signal" --session-id "fixed"
  web:
    dir: "web"
    cmds:
      - pnpm run dev
    env:
      NODE_OPTIONS: "--import ./instrument.server.mjs"
  e2e:
    dir: "web"
    cmds:
      - pnpm exec tsx scripts/e2e-test.ts
