/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerSessionIdCodecRouteImport } from './routes/viewer.$sessionId.$codec'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerSessionIdCodecRoute = ViewerSessionIdCodecRouteImport.update({
  id: '/viewer/$sessionId/$codec',
  path: '/viewer/$sessionId/$codec',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/viewer/$sessionId/$codec': typeof ViewerSessionIdCodecRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/viewer/$sessionId/$codec': typeof ViewerSessionIdCodecRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/viewer/$sessionId/$codec': typeof ViewerSessionIdCodecRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/viewer/$sessionId/$codec'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/viewer/$sessionId/$codec'
  id: '__root__' | '/' | '/viewer/$sessionId/$codec'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewerSessionIdCodecRoute: typeof ViewerSessionIdCodecRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$sessionId/$codec': {
      id: '/viewer/$sessionId/$codec'
      path: '/viewer/$sessionId/$codec'
      fullPath: '/viewer/$sessionId/$codec'
      preLoaderRoute: typeof ViewerSessionIdCodecRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewerSessionIdCodecRoute: ViewerSessionIdCodecRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
